version: "3.8"

services:
  database:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PMS
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"

volumes:
  postgres:
